name: SnakeSvg
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Snake SVG
      uses: Platane/snk/svg-only@v3
      with:
        github_user_name: MinmusLin
        outputs: |
          assets/Snake.svg
